apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policy
  namespace: bonus
spec:
  podSelector:
    matchLabels:
      app: wordpress
  policyTypes:
    - Ingress
    - Egress
